config_version: "1.0.0"
repo:
  url: "https://github.com/modelmapper/modelmapper.git"
  branch: "main"

execution_plan:
  mode: "tests"
  ignore_failures: true
  test_command: "mvn test -Dtest=!TypesTest -Dsurefire.failIfNoSpecifiedTests=false"
  granularity: "commits"
  num_commits: 500
  num_runs: 30
  num_repeats: 1
  newest_commit: "7f345d2a7e5c13738dd1ff39512367e0eebaf39f"
  search_strategy: "naive"
  randomize_tasks: true
  batch_size: 100
  compile_commands:
    - "mvn clean test-compile"
    - "mvn test -Dtest=!TypesTest -Dsurefire.failIfNoSpecifiedTests=false"

limits:
  temperature_safe_limit: 65000
  energy_regression_percent: 20

tracked_file_extensions:
  - "java"
  - "xml"
  - "properties"
  - "yaml"
  - "yml"

cpu_thermal_file: "/sys/class/thermal/thermal_zone0/temp"

regression_detection:
  min_commits_before: 0
